### PR TITLE
CI fixes

### PR DESCRIPTION
**Pull request by Be-ing**
instead of specifying individual crates

should fix CI for #22

### CODE REVIEW

**Comment by Be-ing** [comment]
Oof CI is broken for Rust 1.56 now because Cargo.lock wasn't committed :/

**Comment by Be-ing** [comment]
> Oof CI is broken for Rust 1.56 now because Cargo.lock wasn't committed :/

Fortunately installing old versions of Rust with `rustup` is easy :) I committed a Cargo.lock that works with Rust 1.56.

**Comment by orottier** [comment]
Nice work, but it seems no tests are run at all.
Not entirely sure how this works but specifying `cargo test --workspace --all-targets --all-features` does actually run a few tests. Perhaps specify these as args, also for the `check` task?

**Comment by Be-ing** [comment]
Good catch. Adding `--workspace` is required.

**Review by orottier — APPROVED** [review]

**Pull request merged**
